spring:
  datasource:
    url: jdbc:p6spy:mysql:///mblog?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  freemarker:
    suffix: .html
    content-type: text/html
    enabled: true
    cache: false
    template-loader-path: classpath:/templates/
    charset: UTF-8
  redis:
    host: localhost
    port: 6379
    database: 2
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
      repositories:
        enabled: true
  rabbitmq:
    username: admin
    password: admin
    host: 39.102.102.179
    port: 5672

file:
  upload:
    dir: ${user.dir}/upload