spring:
  datasource:
    url: jdbc:mysql:///mblog?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    suffix: .html
    content-type: text/html
    enabled: true
    cache: false
    template-loader-path: classpath:/templates/
    charset: UTF-8
  redis:
    host: localhost
    port: 6379
    database: 2
logging:
  level:
    com.usth.mblog.mapper: debug

file:
  upload:
    dir: ${user.dir}/upload